-- VHDL Entity alien_game_lib.alien_hit_logic.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 17:22:10 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_hit_logic IS
   PORT( 
      alien_x  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y : IN     std_logic_vector (7 DOWNTO 0);
      hit      : OUT    std_logic
   );

-- Declarations

END alien_hit_logic ;

--
-- VHDL Architecture alien_game_lib.alien_hit_logic.struct
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 17:22:09 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF alien_hit_logic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din0 : std_logic;
   SIGNAL hit2 : std_logic;


   -- Component Declarations
   COMPONENT vector_compare
   PORT (
      input_1 : IN     std_logic_vector (7 DOWNTO 0);
      input_2 : IN     std_logic_vector (7 DOWNTO 0);
      hit     : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : vector_compare USE ENTITY alien_game_lib.vector_compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   hit <= din0 AND hit2;

   -- Instance port mappings.
   U_0 : vector_compare
      PORT MAP (
         input_1 => alien_x,
         input_2 => bullet_x,
         hit     => din0
      );
   U_1 : vector_compare
      PORT MAP (
         input_1 => alien_y,
         input_2 => bullet_y,
         hit     => hit2
      );

END struct;
