-- VHDL Entity alien_game_lib.alien_hp.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-316-SPC)
--          at - 18:52:46 19.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_hp IS
   PORT( 
      clk     : IN     std_logic;
      hit     : IN     std_logic;
      rst     : IN     std_logic;
      hit_out : OUT    std_logic_vector (1 DOWNTO 0)
   );

-- Declarations

END alien_hp ;

--
-- VHDL Architecture alien_game_lib.alien_hp.fsm
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-316-SPC)
--          at - 19:20:39 19.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF alien_hp IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3,
      s4,
      s5,
      s6
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(23 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(23 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s4 : std_logic;
   SIGNAL csm_to_s5 : std_logic;
   SIGNAL csm_to_s6 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      current_state,
      hit
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s4 <= '0';
      csm_to_s5 <= '0';
      csm_to_s6 <= '0';
      CASE current_state IS
         WHEN s0 => 
            IF (hit = '1') THEN 
               next_state <= s4;
               csm_to_s4 <= '1';
            ELSE
               next_state <= s0;
            END IF;
         WHEN s1 => 
            IF (hit = '1') THEN 
               next_state <= s5;
               csm_to_s5 <= '1';
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF (hit = '1') THEN 
               next_state <= s6;
               csm_to_s6 <= '1';
            ELSE
               next_state <= s2;
            END IF;
         WHEN s3 => 
            next_state <= s3;
         WHEN s4 => 
            next_state <= s1;
         WHEN s5 => 
            next_state <= s2;
         WHEN s6 => 
            next_state <= s3;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN s0 => 
            hit_out <= "00";
         WHEN s1 => 
            hit_out <= "01";
         WHEN s2 => 
            hit_out <= "10";
         WHEN s3 => 
            hit_out <= "11";
         WHEN s4 => 
            hit_out <= "00";
         WHEN s5 => 
            hit_out <= "01";
         WHEN s6 => 
            hit_out <= "10";
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s4,
      csm_to_s5,
      csm_to_s6
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s4 = '1') THEN
         csm_next_timer <= "101000000011101110000110"; -- no cycles(10500999)-1=10500998
      ELSIF (csm_to_s5 = '1') THEN
         csm_next_timer <= "101000000011011110011111"; -- no cycles(10500000)-1=10499999
      ELSIF (csm_to_s6 = '1') THEN
         csm_next_timer <= "101000000011011110011111"; -- no cycles(10500000)-1=10499999
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
