-- VHDL Entity alien_game_lib.c2_t2_interactive_effect_on_matrix.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 16:24:10  5.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_interactive_effect_on_matrix IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t2_interactive_effect_on_matrix ;

--
-- VHDL Architecture alien_game_lib.c2_t2_interactive_effect_on_matrix.struct
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 16:24:01  5.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t2_interactive_effect_on_matrix IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5 : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout4 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout5 <= "11110010";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout2 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout3 <= "11110010";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout <= "101100000000101100101111";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout1 <= "101100000000101100101111";

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(dout, dout1, btn)
   BEGIN
      CASE btn(0) IS
      WHEN '0' => color_BGR <= dout;
      WHEN '1' => color_BGR <= dout1;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout4, dout5, btn)
   BEGIN
      CASE btn(2) IS
      WHEN '0' => y_coord <= dout4;
      WHEN '1' => y_coord <= dout5;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(dout2, dout3, btn)
   BEGIN
      CASE btn(1) IS
      WHEN '0' => x_coord <= dout2;
      WHEN '1' => x_coord <= dout3;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

END struct;
