-- VHDL Entity alien_game_lib.c3_t1_basic_alien.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-310-SPC)
--          at - 13:04:21 23.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t1_basic_alien IS
   PORT( 
      clk     : IN     std_logic;
      enable  : IN     std_logic;
      hit_out : IN     std_logic_vector (3 DOWNTO 0);
      rst     : IN     std_logic;
      color   : OUT    std_logic_vector (23 DOWNTO 0);
      x       : OUT    std_logic_vector (7 DOWNTO 0);
      y       : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c3_t1_basic_alien ;

--
-- VHDL Architecture alien_game_lib.c3_t1_basic_alien.struct
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-310-SPC)
--          at - 13:16:47 23.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c3_t1_basic_alien IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL alien_direction : std_logic;
   SIGNAL dout            : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1           : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2           : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout3           : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL x_internal : std_logic_vector (7 DOWNTO 0);


   -- Component Declarations
   COMPONENT coordinate
   PORT (
      alien_direction : IN     std_logic ;
      clk             : IN     std_logic ;
      enable          : IN     std_logic ;
      rst_n           : IN     std_logic ;
      x               : OUT    std_logic_vector (7 DOWNTO 0);
      y               : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT direction
   PORT (
      clock           : IN     std_logic ;
      enable          : IN     std_logic ;
      rst             : IN     std_logic ;
      x               : IN     std_logic_vector (7 DOWNTO 0);
      alien_direction : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : coordinate USE ENTITY alien_game_lib.coordinate;
   FOR ALL : direction USE ENTITY alien_game_lib.direction;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout3 <= "101100111111110101011111";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout2 <= "000000000000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout1 <= "111111110000000000000000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'omux'
   u_3combo_proc: PROCESS(dout3, dout, dout1, dout2, hit_out)
   BEGIN
      color <= (OTHERS => 'X');
      CASE hit_out IS
      WHEN "0001" => color <= dout3;
      WHEN "0010" => color <= dout;
      WHEN "0100" => color <= dout1;
      WHEN "1000" => color <= dout2;
      WHEN OTHERS => color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- Instance port mappings.
   U_1 : coordinate
      PORT MAP (
         alien_direction => alien_direction,
         clk             => clk,
         enable          => enable,
         rst_n           => rst,
         x               => x_internal,
         y               => y
      );
   U_0 : direction
      PORT MAP (
         clock           => clk,
         enable          => enable,
         rst             => rst,
         x               => x_internal,
         alien_direction => alien_direction
      );

   -- Implicit buffered output assignments
   x <= x_internal;

END struct;
