-- VHDL Entity alien_game_lib.color_effect.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 19:16:35 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY color_effect IS
   PORT( 
      clk         : IN     std_logic;
      rst         : IN     std_logic;
      win_or_lose : IN     std_logic;
      color       : OUT    std_logic_vector (23 DOWNTO 0);
      x           : OUT    std_logic_vector (7 DOWNTO 0);
      y           : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END color_effect ;

--
-- VHDL Architecture alien_game_lib.color_effect.struct
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 20:19:38 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF color_effect IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);


   -- Component Declarations
   COMPONENT lose_effect
   PORT (
      clk : IN     std_logic ;
      rst : IN     std_logic ;
      x   : OUT    std_logic_vector (7 DOWNTO 0);
      y   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : lose_effect USE ENTITY alien_game_lib.lose_effect;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout <= "000000000000000011111111";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout1 <= "000000001111111100000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout, dout1, win_or_lose)
   BEGIN
      CASE win_or_lose IS
      WHEN '0' => color <= dout;
      WHEN '1' => color <= dout1;
      WHEN OTHERS => color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- Instance port mappings.
   U_0 : lose_effect
      PORT MAP (
         clk => clk,
         rst => rst,
         x   => x,
         y   => y
      );

END struct;
