-- VHDL Entity alien_game_lib.decrementer.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 17:38:50  4.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY decrementer IS
   PORT( 
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END decrementer ;

--
-- VHDL Architecture alien_game_lib.decrementer.struct
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 18:05:10  4.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL COUT  : std_logic;
   SIGNAL COUT1 : std_logic;
   SIGNAL SUM   : std_logic;
   SIGNAL SUM1  : std_logic;
   SIGNAL SUM2  : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout0 : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'split'
   SIGNAL mw_U_3temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT full_adder
   PORT (
      A    : IN     std_logic ;
      B    : IN     std_logic ;
      CIN  : IN     std_logic ;
      COUT : OUT    std_logic ;
      SUM  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : full_adder USE ENTITY alien_game_lib.full_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout2 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout4 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout5 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_4' of 'merge'
   result <= SUM2 & SUM1 & SUM;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'split'
   mw_U_3temp_din <= value;
   u_3combo_proc: PROCESS (mw_U_3temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_3temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout1 <= temp_din(1);
      dout3 <= temp_din(2);
   END PROCESS u_3combo_proc;

   -- Instance port mappings.
   U_0 : full_adder
      PORT MAP (
         A    => dout1,
         B    => dout2,
         CIN  => COUT,
         COUT => COUT1,
         SUM  => SUM1
      );
   U_1 : full_adder
      PORT MAP (
         A    => dout0,
         B    => dout,
         CIN  => dout5,
         COUT => COUT,
         SUM  => SUM
      );
   U_2 : full_adder
      PORT MAP (
         A    => dout3,
         B    => dout4,
         CIN  => COUT1,
         COUT => OPEN,
         SUM  => SUM2
      );

END struct;
