-- VHDL Entity alien_game_lib.direction.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-314-SPC)
--          at - 16:41:24 13.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY direction IS
   PORT( 
      clock           : IN     std_logic;
      enable          : IN     std_logic;
      rst             : IN     std_logic;
      x               : IN     std_logic_vector (7 DOWNTO 0);
      alien_direction : OUT    std_logic
   );

-- Declarations

END direction ;

--
-- VHDL Architecture alien_game_lib.direction.struct
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-314-SPC)
--          at - 16:42:28 13.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF direction IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL alien_direction_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   alien_direction_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clock, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_2reg_cval <= '1';
      ELSIF (RISING_EDGE(clock)) THEN
         mw_U_2reg_cval <= dout;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(alien_direction_internal, dout2, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout <= alien_direction_internal;
      WHEN '1' => dout <= dout2;
      WHEN OTHERS => dout <= 'X';
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'or'
   dout1 <= x(0) OR x(7);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'xor'
   dout2 <= alien_direction_internal XOR dout1;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   alien_direction <= alien_direction_internal;

END struct;
