-- VHDL Entity alien_game_lib.game_logic_mux.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 18:52:28 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY game_logic_mux IS
   PORT( 
      alien_color   : IN     std_logic_vector (23 DOWNTO 0);
      alien_x       : IN     std_logic_vector (7 DOWNTO 0);
      alien_y       : IN     std_logic_vector (7 DOWNTO 0);
      bullet_color  : IN     std_logic_vector (23 DOWNTO 0);
      bullet_x      : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y      : IN     std_logic_vector (7 DOWNTO 0);
      effect_color  : IN     std_logic_vector (23 DOWNTO 0);
      effect_x      : IN     std_logic_vector (7 DOWNTO 0);
      effect_y      : IN     std_logic_vector (7 DOWNTO 0);
      gun_color     : IN     std_logic_vector (23 DOWNTO 0);
      gun_x         : IN     std_logic_vector (7 DOWNTO 0);
      gun_y         : IN     std_logic_vector (7 DOWNTO 0);
      module_select : IN     std_logic_vector (1 DOWNTO 0);
      output_color  : OUT    std_logic_vector (23 DOWNTO 0);
      output_x      : OUT    std_logic_vector (7 DOWNTO 0);
      output_y      : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END game_logic_mux ;

--
-- VHDL Architecture alien_game_lib.game_logic_mux.struct
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 18:52:27 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF game_logic_mux IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(alien_color, gun_color, bullet_color, 
                          effect_color, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => output_color <= alien_color;
      WHEN "01" => output_color <= gun_color;
      WHEN "10" => output_color <= bullet_color;
      WHEN "11" => output_color <= effect_color;
      WHEN OTHERS => output_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(alien_y, gun_y, bullet_y, effect_y, 
                          module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => output_y <= alien_y;
      WHEN "01" => output_y <= gun_y;
      WHEN "10" => output_y <= bullet_y;
      WHEN "11" => output_y <= effect_y;
      WHEN OTHERS => output_y <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(alien_x, gun_x, bullet_x, effect_x, 
                          module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => output_x <= alien_x;
      WHEN "01" => output_x <= gun_x;
      WHEN "10" => output_x <= bullet_x;
      WHEN "11" => output_x <= effect_x;
      WHEN OTHERS => output_x <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- Instance port mappings.

END struct;
