-- VHDL Entity alien_game_lib.gun_left_shifter.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-316-SPC)
--          at - 17:17:40  6.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY gun_left_shifter IS
   PORT( 
      x_in  : IN     std_logic_vector (7 DOWNTO 0);
      x_out : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END gun_left_shifter ;

--
-- VHDL Architecture alien_game_lib.gun_left_shifter.struct
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-304-SPC)
--          at - 17:17:49 19.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF gun_left_shifter IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'fixshift'
   SIGNAL mw_U_0temp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout2 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_0' of 'fixshift'
   dout <= mw_U_0temp_dout;
   u_0combo_proc: PROCESS (x_in)
   BEGIN
      mw_U_0temp_dout <= (OTHERS => '0');
      mw_U_0temp_dout(7 DOWNTO 1) <= x_in(6 + 0 DOWNTO 0);
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(dout, x_in, dout1)
   BEGIN
      CASE dout1 IS
      WHEN '0' => x_out <= dout;
      WHEN '1' => x_out <= x_in;
      WHEN OTHERS => x_out <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or1'
   dout1 <= dout2 OR dout(7);

   -- Instance port mappings.

END struct;
