-- VHDL Entity alien_game_lib.incrementer.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 17:08:21  4.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY incrementer IS
   PORT( 
      value  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END incrementer ;

--
-- VHDL Architecture alien_game_lib.incrementer.struct
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 17:10:28  4.02.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF incrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry  : std_logic;
   SIGNAL carry1 : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout0  : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL sum    : std_logic;
   SIGNAL sum1   : std_logic;
   SIGNAL sum2   : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_6' of 'split'
   SIGNAL mw_U_6temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_3' of 'merge'
   result <= sum2 & sum1 & sum;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'split'
   mw_U_6temp_din <= value;
   u_6combo_proc: PROCESS (mw_U_6temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_6temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout1 <= temp_din(1);
      dout2 <= temp_din(2);
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_0 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout0,
         sw1   => dout,
         carry => carry,
         sum   => sum
      );
   U_1 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout2,
         sw1   => carry1,
         carry => OPEN,
         sum   => sum2
      );
   U_2 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout1,
         sw1   => carry,
         carry => carry1,
         sum   => sum1
      );

END struct;
