-- VHDL Entity alien_game_lib.move_alien.symbol
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 19:31:31 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY move_alien IS
   PORT( 
      clk : IN     std_logic;
      rst : IN     std_logic;
      y   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END move_alien ;

--
-- VHDL Architecture alien_game_lib.move_alien.fsm
--
-- Created:
--          by - cvalzu.UNKNOWN (HTC219-313-SPC)
--          at - 20:06:34 17.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF move_alien IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3,
      s4,
      s5,
      s6,
      s7
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(29 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(29 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s1 : std_logic;
   SIGNAL csm_to_s2 : std_logic;
   SIGNAL csm_to_s3 : std_logic;
   SIGNAL csm_to_s4 : std_logic;
   SIGNAL csm_to_s5 : std_logic;
   SIGNAL csm_to_s6 : std_logic;
   SIGNAL csm_to_s7 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s1 <= '0';
      csm_to_s2 <= '0';
      csm_to_s3 <= '0';
      csm_to_s4 <= '0';
      csm_to_s5 <= '0';
      csm_to_s6 <= '0';
      csm_to_s7 <= '0';
      CASE current_state IS
         WHEN s0 => 
            next_state <= s1;
            csm_to_s1 <= '1';
         WHEN s1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s2;
               csm_to_s2 <= '1';
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s3;
               csm_to_s3 <= '1';
            ELSE
               next_state <= s2;
            END IF;
         WHEN s3 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s4;
               csm_to_s4 <= '1';
            ELSE
               next_state <= s3;
            END IF;
         WHEN s4 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s7;
               csm_to_s7 <= '1';
            ELSE
               next_state <= s4;
            END IF;
         WHEN s5 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s6;
               csm_to_s6 <= '1';
            ELSE
               next_state <= s5;
            END IF;
         WHEN s6 => 
            next_state <= s6;
         WHEN s7 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s5;
               csm_to_s5 <= '1';
            ELSE
               next_state <= s7;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN s1 => 
            y <= "00000001";
         WHEN s2 => 
            y <= "00000010";
         WHEN s3 => 
            y <= "00000100";
         WHEN s4 => 
            y <= "00001000";
         WHEN s5 => 
            y <= "00100000";
         WHEN s6 => 
            y <= "01000000";
         WHEN s7 => 
            y <= "00010000";
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s1,
      csm_to_s2,
      csm_to_s3,
      csm_to_s4,
      csm_to_s5,
      csm_to_s6,
      csm_to_s7
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s1 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSIF (csm_to_s2 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSIF (csm_to_s3 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSIF (csm_to_s4 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSIF (csm_to_s5 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSIF (csm_to_s6 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSIF (csm_to_s7 = '1') THEN
         csm_next_timer <= "111011100110101100100111111111"; -- no cycles(1000000000)-1=999999999
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
