-- VHDL Entity alien_game_lib.vector_compare.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-315-SPC)
--          at - 15:32:58 18.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY vector_compare IS
   PORT( 
      input_1 : IN     std_logic_vector (7 DOWNTO 0);
      input_2 : IN     std_logic_vector (7 DOWNTO 0);
      hit     : OUT    std_logic
   );

-- Declarations

END vector_compare ;

--
-- VHDL Architecture alien_game_lib.vector_compare.struct
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-315-SPC)
--          at - 15:32:57 18.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF vector_compare IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL dout4 : std_logic;
   SIGNAL dout5 : std_logic;
   SIGNAL dout6 : std_logic;
   SIGNAL dout7 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and1'
   dout <= input_1(0) AND input_2(0);

   -- ModuleWare code(v1.12) for instance 'U_2' of 'and1'
   dout1 <= input_1(1) AND input_2(1);

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and1'
   dout2 <= input_1(2) AND input_2(2);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and1'
   dout5 <= input_1(5) AND input_2(5);

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and1'
   dout3 <= input_1(3) AND input_2(3);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and1'
   dout7 <= input_1(7) AND input_2(7);

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and1'
   dout6 <= input_1(6) AND input_2(6);

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and1'
   dout4 <= input_1(4) AND input_2(4);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'or'
   hit <= dout OR dout1 OR dout2 OR dout3 OR dout4 OR dout5 OR dout6
          OR dout7;

   -- Instance port mappings.

END struct;
