-- VHDL Entity alien_game_lib.victory.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 14:20:20  5.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY victory IS
   PORT( 
      clk   : IN     std_logic;
      rst_n : IN     std_logic;
      color : OUT    std_logic_vector (23 DOWNTO 0);
      x     : OUT    std_logic_vector (7 DOWNTO 0);
      y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END victory ;

--
-- VHDL Architecture alien_game_lib.victory.struct
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 14:20:20  5.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF victory IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL q     : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL x_internal : std_logic_vector (7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'fixshift'
   SIGNAL mw_U_3temp_dout : std_logic_vector(7 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   q <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= "10000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout1;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'buff'
   x_internal <= dout;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'buff'
   dout1 <= x_internal;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   y <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   color <= "111111111100000000001000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'fixshift'
   dout <= mw_U_3temp_dout;
   u_3combo_proc: PROCESS (q)
   BEGIN
      mw_U_3temp_dout <= (OTHERS => '0');
      mw_U_3temp_dout(6 DOWNTO 0) <= q(7 + 0 DOWNTO 1 + 0);
   END PROCESS u_3combo_proc;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   x <= x_internal;

END struct;
