-- VHDL Entity alien_game_lib.victory_state.symbol
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 14:54:14  5.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY victory_state IS
   PORT( 
      clk   : IN     std_logic;
      rst   : IN     std_logic;
      color : OUT    std_logic_vector (23 DOWNTO 0);
      x     : OUT    std_logic_vector (7 DOWNTO 0);
      y     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END victory_state ;

--
-- VHDL Architecture alien_game_lib.victory_state.fsm
--
-- Created:
--          by - txdava.UNKNOWN (HTC219-322-SPC)
--          at - 14:54:06  5.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF victory_state IS

   TYPE STATE_TYPE IS (
      s0,
      s1,
      s2,
      s3,
      s4
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(2 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(2 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s1 : std_logic;
   SIGNAL csm_to_s2 : std_logic;
   SIGNAL csm_to_s3 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s1 <= '0';
      csm_to_s2 <= '0';
      csm_to_s3 <= '0';
      CASE current_state IS
         WHEN s0 => 
            next_state <= s1;
            csm_to_s1 <= '1';
         WHEN s1 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s2;
               csm_to_s2 <= '1';
            ELSE
               next_state <= s1;
            END IF;
         WHEN s2 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s3;
               csm_to_s3 <= '1';
            ELSE
               next_state <= s2;
            END IF;
         WHEN s3 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s0;
            ELSE
               next_state <= s3;
            END IF;
         WHEN s4 => 
            IF (rst = '1') THEN 
               next_state <= s0;
            ELSE
               next_state <= s4;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN

      -- Combined Actions
      CASE current_state IS
         WHEN s0 => 
            x<= "00000001";
            y<= "10000000";
            color <= "111111111100000000001000";
         WHEN s1 => 
            x <= "00000001";
            y <= "00000001";
            color <= "111111111100000000001000";
         WHEN s2 => 
            x <= "10000000";
            y <= "00000001";
            color <= "111111111100000000001000";
         WHEN s3 => 
            x <= "10000000";
            y <= "10000000";
            color <= "111111111100000000001000";
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s1,
      csm_to_s2,
      csm_to_s3
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s1 = '1') THEN
         csm_next_timer <= "100"; -- no cycles(5)-1=4
      ELSIF (csm_to_s2 = '1') THEN
         csm_next_timer <= "100"; -- no cycles(5)-1=4
      ELSIF (csm_to_s3 = '1') THEN
         csm_next_timer <= "100"; -- no cycles(5)-1=4
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
